version: "3.9"
services:
  curling-score-tracker:
    build:
      context: .
    volumes:
      - ./src:/app/src           # Mount source code for live updates
      - ./data:/app/data         # Mount data directory
    stdin_open: true
    tty: true
